version: "3.1"

services:
   mysql:
     image: "mysql:5.7"
     container_name: "mysql-db"
     restart: "unless-stopped"
     expose:
       - "3306"
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "LayerArchitectureExample"
