-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 15:23:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LayerArchitectureExample
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LayerArchitectureExample` ;

-- -----------------------------------------------------
-- Schema LayerArchitectureExample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LayerArchitectureExample` DEFAULT CHARACTER SET utf8 ;
USE `LayerArchitectureExample` ;

-- -----------------------------------------------------
-- Table `TodoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TodoList` ;

CREATE TABLE IF NOT EXISTS `TodoList` (
  `Id` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DueDate` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
;


-- -----------------------------------------------------
-- Table `Todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Todo` ;

CREATE TABLE IF NOT EXISTS `Todo` (
  `Id` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DueDate` DATETIME NULL,
  `TodoListId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `fk_Todo_TodoList_idx` (`TodoListId` ASC),
  CONSTRAINT `fk_Todo_TodoList`
    FOREIGN KEY (`TodoListId`)
    REFERENCES `TodoList` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
